name: Github Pages

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: macos-12
    strategy:
      matrix:
        swift: ["5.7"]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Webber
        run: brew install swifweb/tap/webber

      - name: Release Webber
        run: webber release

      - name: Config Git
        run: |
          git config --global user.name 'baekteun'
          git config --global user.email 'baegteun@gmail.com'
          git config pull.rebase false
          git fetch --all
          git checkout -t origin/gh-pages
          git pull origin gh-pages --allow-unrelated-histories

      - name: Remove Prev Web
        run: |
          mv ./docs/index.html ./index.html
          rm -rf ./docs

      - name: Result move to docs
        run: |
          rm -rf .webber/release/index.html
          mv .webber/release/ .
          mv release docs
          mv ./index.html ./docs/index.html

      - name: Create CNAME file in docs
        run: |
          touch docs/CNAME
          echo "baegteun.com" >> docs/CNAME

      - name: git commit & push
        run: |
          git add -A
          git commit -m ":rocket: :: github pages deploy"
          git push

